spring:
  datasource:
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: system
   password: root
   driver-class-name: oracle.jdbc.OracleDriver
  jpa:
   open-in-view: true
   database-platform: org.hibernate.dialect.Oracle10gDialect
   generate-ddl: true
   properties:
     hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddl-auto: update
   show-sql: true
 